import React from "react";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";
import { Printer } from "lucide-react";

import type { Schema } from "@/types/api-types";

type DelegationResponse = Schema["DelegationResponse"];


interface DelegationReportProps {
  delegation: DelegationResponse;
  primaryName: string;
  deputyName: string;
  positionTitle: string;
}

export const DelegationReport: React.FC<DelegationReportProps> = ({ delegation, primaryName, deputyName, positionTitle }) => {
  return (
    <div className="relative">
      {/* Print Button - Hidden when printing */}
      <div className="flex justify-end mb-4 print:hidden">
        <Button 
          onClick={() => window.print()} 
          className="bg-slate-900 hover:bg-black text-white gap-2 shadow-lg"
        >
          <Printer size={16} />
          Print ISO Document
        </Button>
      </div>


    <div className="p-10 max-w-4xl mx-auto bg-white text-black border shadow-sm print:border-0 print:shadow-none print:p-0">
      {/* Header */}
      <div className="flex justify-between border-b-2 border-black pb-4 mb-8">
        <div>
          <h1 className="text-2xl font-bold uppercase">Laboratory Authority Delegation</h1>
          <p className="text-sm">ISO 17025 Compliance Document - Section 6.2.5</p>
        </div>
        <div className="text-right">
          <p className="font-bold">Record ID: DEL-{delegation.id}</p>
          <p>Status: {delegation.status.toUpperCase()}</p>
        </div>
      </div>

      {/* Primary Parties */}
      <div className="grid grid-cols-2 gap-8 mb-8">
        <div className="space-y-1">
          <h3 className="text-xs font-bold text-gray-500 uppercase">Primary Authority (Absent)</h3>
          <p className="text-lg font-semibold">{primaryName}</p>
        </div>
        <div className="space-y-1">
          <h3 className="text-xs font-bold text-gray-500 uppercase">Deputy Authority (Acting)</h3>
          <p className="text-lg font-semibold">{deputyName}</p>
        </div>
      </div>

      {/* Delegation Scope */}
      <div className="bg-gray-50 p-4 rounded mb-8 border">
        <h3 className="text-xs font-bold text-gray-500 uppercase mb-2">Delegated Position & Technical Field</h3>
        <p className="text-xl font-bold">{positionTitle}</p>
        <p className="mt-2 text-sm text-gray-700">
          <strong>Authorized Scope:</strong> {delegation.scope || "Full operational and technical authority for the specified position."}
        </p>
      </div>

      {/* Validity Period */}
      <div className="grid grid-cols-2 gap-8 mb-12">
        <div className="border-l-4 border-black pl-4">
          <p className="text-xs font-bold text-gray-500 uppercase">Effective From</p>
          <p className="text-md">{format(new Date(delegation.start_date), "PPP p")}</p>
        </div>
        <div className="border-l-4 border-black pl-4">
          <p className="text-xs font-bold text-gray-500 uppercase">Effective Until</p>
          <p className="text-md">{format(new Date(delegation.end_date), "PPP p")}</p>
        </div>
      </div>

      {/* Audit & Verification */}
      <div className="mt-20 border-t pt-8">
        <div className="grid grid-cols-2 gap-20">
          <div className="border-t border-black pt-2">
            <p className="text-xs font-bold uppercase">Authorized By (Digital Signature)</p>
            <p className="text-sm italic">System Validated: {format(new Date(delegation.created_at), "yyyy-MM-dd HH:mm")}</p>
          </div>
          <div className="border-t border-black pt-2">
            <p className="text-xs font-bold uppercase">Quality Manager Review</p>
            <div className="h-10"></div>
          </div>
        </div>
      </div>

      <footer className="mt-20 text-[10px] text-gray-400 text-center">
        This document was electronically generated by BLIMS-V3. 
        Alteration of this record is a violation of ISO 17025 data integrity standards.
      </footer>
    </div>
  </div>
  );
};