// @/features/saas/organizations/organizations.store.ts
import { create } from "zustand";
import type { components } from "@/generated/saas/api";

// Safely extract the exact schema type from your autogenerated openapi schema
export type Organization = components["schemas"]["OrganizationRead"];

type OrganizationsUIState = {
  selectedOrganization: Organization | null;
  isFormModalOpen: boolean;
  
  // Clean UI Actions
  setSelectedOrganization: (organization: Organization | null) => void;
  openFormModal: (organization?: Organization | null) => void;
  closeFormModal: () => void;
};

export const useOrganizationsUIStore = create<OrganizationsUIState>((set) => ({
  selectedOrganization: null,
  isFormModalOpen: false,

  setSelectedOrganization: (organization) => 
    set({ selectedOrganization: organization }),

  openFormModal: (organization = null) => 
    set({ selectedOrganization: organization, isFormModalOpen: true }),

  closeFormModal: () => 
    set({ selectedOrganization: null, isFormModalOpen: false }),
}));